"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function NewCustomerPage() {
  const router = useRouter();
  const [form, setForm] = useState({ name: "", email: "", mobile: "", password: "", status: "Active" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/customers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.message ?? "Unable to add customer."); router.push(`/admin/customers/${payload.data.id}`); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to add customer."); } finally { setSaving(false); } };
  const field = (key: keyof typeof form, label: string, type = "text") => <label className="block text-sm font-medium text-[#4d4541]">{label}<input type={type} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} required={key === "name" || key === "email"} className="mt-2 h-11 w-full rounded-lg border border-[#e1d9d5] bg-white px-3.5 outline-none transition focus:border-[#a87567] focus:ring-2 focus:ring-[#a87567]/10" /></label>;
  return <div className="min-h-[calc(100vh-72px)] bg-[#faf8f6]"><div className="border-b border-[#eee6e1] bg-white"><div className="mx-auto max-w-4xl px-5 py-6 lg:px-8"><Link href="/admin/customers" className="text-sm text-[#857974] hover:text-[#292321]">← Back to customers</Link><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-[#a87567]">Customer management</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-[#292321]">Add customer</h1><p className="mt-1 text-sm text-[#8b817c]">Create a customer profile and provide a temporary sign-in password.</p></div></div><form onSubmit={save} className="mx-auto max-w-4xl px-5 py-8 lg:px-8"><section className="rounded-xl border border-[#eee6e1] bg-white p-5 shadow-sm sm:p-7"><h2 className="text-base font-semibold text-[#292321]">Profile details</h2><div className="mt-6 grid gap-5 sm:grid-cols-2">{field("name", "Full name")}{field("email", "Email address", "email")}{field("mobile", "Mobile number", "tel")}{field("password", "Temporary password", "password")}<label className="block text-sm font-medium text-[#4d4541]">Account status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-2 h-11 w-full rounded-lg border border-[#e1d9d5] bg-white px-3.5 outline-none focus:border-[#a87567]"><option>Active</option><option>Inactive</option></select></label></div>{error && <p className="mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}</section><div className="mt-6 flex justify-end gap-3"><Link href="/admin/customers" className="inline-flex h-11 items-center rounded-lg border border-[#ded6d1] px-5 text-sm font-medium text-[#625954]">Cancel</Link><button disabled={saving} className="inline-flex h-11 items-center rounded-lg bg-[#292321] px-5 text-sm font-medium text-white hover:bg-[#403936] disabled:opacity-60">{saving ? "Saving…" : "Create customer"}</button></div></form></div>;
}
