"use client";
import { useEffect, useState } from "react";
import { protectedSeoPath, type SeoEntry } from "@/lib/seo-config";
type Page = { path: string; title: string; description?: string };
const empty: SeoEntry = { title: "", description: "", image: "", canonical: "", noindex: false };
export default function SeoManager() {
  const [pages, setPages] = useState<Page[]>([]);
  const [saved, setSaved] = useState<Record<string, SeoEntry>>({});
  const [path, setPath] = useState("/");
  const [entry, setEntry] = useState<SeoEntry>(empty);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("Loading SEO settings…");
  const [busy, setBusy] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [dirty, setDirty] = useState(false);
  useEffect(() => { fetch("/api/admin/seo").then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.message); setPages(data.pages); setSaved(data.saved); setEntry(data.saved["/"] || empty); setStatus(""); setLoaded(true); }).catch(e => setStatus(e.message)); }, []);
  const page = pages.find(p => p.path === path);
  const patch = (value: Partial<SeoEntry>) => { setEntry(current => ({ ...current, ...value })); setDirty(true); setStatus(""); };
  async function save() {
    setBusy(true); setStatus("");
    try { const response = await fetch("/api/admin/seo", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ path, entry }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setSaved(current => ({ ...current, [path]: entry })); setDirty(false); setStatus("SEO settings saved. Search engines update on their next crawl."); } catch (e) { setStatus(e instanceof Error ? e.message : "Save failed. Please retry."); } finally { setBusy(false); }
  }
  return <main className="min-h-screen bg-[#f7f8fa] p-4 text-gray-900 sm:p-8">
    <div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-gray-500">Vayziq · Search & social</p><h1 className="mt-2 text-3xl font-bold">SEO Manager</h1><p className="mt-2 text-sm text-gray-600">Men, women & unisex streetwear. Manage each page without editing code.</p></div><button disabled={!loaded || busy || !dirty} onClick={save} className="rounded-xl bg-black px-6 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy ? "Saving…" : "Save changes"}</button></div>
    <div className="grid items-start gap-6 xl:grid-cols-[260px_minmax(0,1fr)]"><aside className="rounded-2xl border border-gray-200 bg-white p-4"><label className="text-xs font-semibold" htmlFor="seo-search">Find a page</label><input id="seo-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Product, category or URL…" className="my-3 w-full rounded-lg border p-3 text-sm" /><div className="max-h-[560px] space-y-1 overflow-y-auto">{pages.filter(p => (p.path + p.title).toLowerCase().includes(search.toLowerCase())).map(p => <button key={p.path} disabled={busy} onClick={() => { if (dirty && !window.confirm("Discard unsaved changes?")) return; setPath(p.path); setEntry(saved[p.path] || { ...empty, noindex: protectedSeoPath(p.path) }); setDirty(false); setStatus(""); }} className={`w-full break-words rounded-lg p-3 text-left text-xs ${path === p.path ? "bg-amber-100 font-bold" : "hover:bg-gray-50"}`}>{p.path}<span className="mt-1 block font-normal text-gray-500">{saved[p.path] ? "Custom SEO" : "Automatic defaults"}</span></button>)}</div></aside>
    <section className="min-w-0 space-y-5"><div className="rounded-2xl border border-gray-200 bg-white p-5 sm:p-7"><div className="mb-6 flex flex-wrap justify-between gap-2"><h2 className="font-semibold">Page settings <span className="ml-2 text-sm font-normal text-gray-500">{path}</span></h2><a href={path} target="_blank" rel="noreferrer" className="text-sm underline">View page ↗</a></div><p className="mb-5 text-xs text-gray-500">Leave a field blank to use its automatic page default. Product and article details remain the fallback.</p><div className="space-y-5">{([ ["title", "SEO title", 100], ["description", "Meta description", 320], ["image", "Social image URL", 2000], ["canonical", "Canonical URL (advanced)", 2000] ] as const).map(([key, label, max]) => <label key={key} className="block text-sm font-medium">{label}{key === "description" ? <textarea rows={3} maxLength={max} value={entry[key]} onChange={e => patch({ [key]: e.target.value })} placeholder={page?.description || "Automatic page description"} className="mt-2 w-full rounded-lg border border-gray-300 p-3 font-normal" /> : <input maxLength={max} value={entry[key]} onChange={e => patch({ [key]: e.target.value })} placeholder={key === "title" ? page?.title : key === "canonical" ? `https://vayziq.com${path}` : "https://… / Recommended: 1200 × 630 image"} className="mt-2 w-full rounded-lg border border-gray-300 p-3 font-normal" />}{(key === "title" || key === "description") && <span className="mt-1 block text-xs font-normal text-gray-500">{entry[key].length} characters · Suggested {key === "title" ? "50–60" : "140–160"}; preview is approximate.</span>}</label>)}<label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={protectedSeoPath(path) || entry.noindex} disabled={protectedSeoPath(path)} onChange={e => patch({ noindex: e.target.checked })} />Exclude this page from search results and sitemap</label>{protectedSeoPath(path) && <p className="text-xs text-gray-500">Shopping and account utility pages are always noindex.</p>}</div></div>
    <div className="rounded-2xl border border-gray-200 bg-white p-6"><p className="mb-4 text-xs font-semibold uppercase tracking-wider text-gray-500">Search preview</p><p className="break-all text-xs text-gray-600">{entry.canonical || `https://vayziq.com${path}`}</p><p className="mt-2 text-xl text-blue-800">{entry.title || page?.title}</p><p className="mt-2 text-sm leading-6 text-gray-600">{entry.description || page?.description || "The page's product, category or article description will be used."}</p>{entry.image && <div role="img" aria-label="Social image preview" className="mt-5 aspect-[1200/630] max-w-lg rounded-lg border bg-cover bg-center" style={{ backgroundImage: `url(${JSON.stringify(entry.image)})` }} />}</div><p role="status" className="text-sm text-gray-700">{status}</p></section></div>
  </main>;
}
