"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
export const placements = { home: "Home slider", "offer-zone": "Home Offer Zone", shop: "Shop slider", search: "Search results slider" };
type Product = { id: number; name: string; sku: string; slug: string };
type ActiveCategory = { name: string; slug: string };
export default function BannerEditor({ id }: { id?: string }) {
  const router = useRouter();
  const [form,setForm] = useState({ title: "", subtitle: "", image: "", link: "/shop", placement: "home", active: true, sortOrder: 0 });
  const [product,setProduct] = useState<Product | null>(null);
  const [categories,setCategories] = useState<ActiveCategory[]>([]);
  const [mode,setMode] = useState("destination");
  const [q,setQ] = useState("");
  const [products,setProducts] = useState<Product[]>([]);
  const [error,setError] = useState("");
  const [busy,setBusy] = useState(false);
  const [loading,setLoading] = useState(Boolean(id));
  useEffect(() => { fetch("/api/categories?status=active").then(async response => { const data = await response.json(); if (response.ok) setCategories(data.categories); }).catch(() => {}); }, []);
  const placementOptions = [...Object.entries(placements), ...categories.map(category => [`category:${category.slug}`, `${category.name} slider`] as [string,string])];
  useEffect(() => { if (!id) return; fetch(`/api/banners/${id}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error("Unable to load banner."); setForm({ ...data.data, link: data.data.link || "", subtitle: data.data.subtitle || "" }); }).catch(error => setError(error.message)).finally(() => setLoading(false)); }, [id]);
  useEffect(() => { if (mode !== "product") return; const controller = new AbortController(); const timer = window.setTimeout(() => { fetch(`/api/admin/product-search?q=${encodeURIComponent(q)}`, { signal: controller.signal }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error("Unable to search products."); setProducts(data.products); }).catch(error => { if (error.name !== "AbortError") setError(error.message); }); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [q,mode]);
  async function upload(file?: File) { if (!file) return; setBusy(true); setError(""); try { const body = new FormData(); body.set("file",file); const response = await fetch("/api/upload/banner", { method: "POST",body }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setForm(current => ({ ...current,image:data.image })); } catch(error) { setError(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } }
  async function save(event: React.FormEvent) { event.preventDefault(); if (mode === "product" && !product) { setError("Select a product from the search results."); return; } setBusy(true); setError(""); try { const response = await fetch(id ? `/api/banners/${id}` : "/api/banners", { method: id ? "PATCH" : "POST", headers: { "Content-Type":"application/json" }, body:JSON.stringify({ ...form, ...(mode === "product" ? { productId:product?.id,link:"" } : {}) }) }); const data=await response.json(); if(!response.ok)throw new Error(data.message);router.push("/admin/banners");router.refresh(); }catch(error){setError(error instanceof Error?error.message:"Save failed.");}finally{setBusy(false);} }
  if (loading) return <p className="p-6">Loading banner…</p>;
  return <main className="min-h-screen bg-[#faf8f6] p-5 sm:p-7"><Link href="/admin/banners" className="text-sm text-[#857974]">← Back to banners</Link><h1 className="mt-5 text-2xl font-semibold">{id ? "Edit banner" : "Add banner"}</h1><form onSubmit={save} className="mt-6 max-w-3xl space-y-5 rounded-xl border bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Placement"><select value={form.placement} onChange={e=>setForm({...form,placement:e.target.value})}>{placementOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Position (lowest first)"><input type="number" min={0} max={100000} value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})} /></Field><Field label="Title (optional)"><input maxLength={150} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} /></Field><Field label="Subtitle (optional)"><input maxLength={300} value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})} /></Field></div><Field label="Banner image"><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void upload(e.target.files?.[0])} /></Field><p className="text-xs text-[#857974]">JPG, PNG or WebP, up to 2 MB. Recommended: 1600 × 600 for sliders; 1000 × 400 for Offer Zone cards. Use an image with its promotional text included, or add a title above.</p>{form.image && <img src={form.image} alt="Banner preview" className="max-h-56 w-full rounded-lg object-contain" />}
  <Field label="Link to"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="destination">Internal destination / existing link</option><option value="product">Search and select a product</option></select></Field>{mode === "product" ? <div><Field label="Search product name or SKU"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Start typing a product name" /></Field>{product && <p className="mt-2 text-sm text-[#9b5c5c]">Selected: {product.name}</p>}<div className="mt-3 max-h-52 overflow-y-auto rounded-lg border">{products.map(item=><button key={item.id} type="button" onClick={()=>setProduct(item)} className={"block w-full border-b p-3 text-left text-sm last:border-0 " +(product?.id===item.id?"bg-[#F8EFEC]":"hover:bg-gray-50")}>{item.name}<span className="block text-xs text-gray-500">{item.sku}</span></button>)}</div></div> : <Field label="Internal destination"><input list="banner-destinations" value={form.link} onChange={e=>setForm({...form,link:e.target.value})} placeholder="/shop" /><datalist id="banner-destinations">{["/shop","/cart", ...categories.map(category => "/" + category.slug)].map(url=><option key={url} value={url} />)}</datalist></Field>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} />Enabled</label>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy || !form.image} className="rounded-lg bg-[#292321] px-5 py-3 text-sm text-white disabled:opacity-40">{busy?"Saving…":"Save banner"}</button></form></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm text-[#4d4541]">{label}<span className="mt-2 block [&_input]:h-11 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:px-3 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:px-3">{children}</span></label>;}
