"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { offerTerms, offerTitle, type OfferRules } from "@/lib/product-offers";

type Form = { code: string; description: string; type: string; value: string; minimumOrder: string; maximumDiscount: string; usageLimit: string; startsAt: string; expiresAt: string; active: boolean; rules: OfferRules };
const blank: Form = { code: "", description: "", type: "percentage", value: "10", minimumOrder: "", maximumDiscount: "", usageLimit: "", startsAt: "", expiresAt: "", active: true, rules: { mode: "same_price", freeRule: "cheapest", freeProductIds: [], productIds: [], buyQuantity: 1, getQuantity: 1, tiers: [{ quantity: 3, price: 399 }, { quantity: 4, price: 299 }], priceMode: "unit" } };
type Product = { id: number; name: string; sku: string; price: string; status: string };
export default function CouponEditor({ id }: { id?: string }) {
  const router = useRouter();
  const [form, setForm] = useState<Form>(blank);
  const [loading, setLoading] = useState(Boolean(id));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [products, setProducts] = useState<Product[]>([]);
  const [productError, setProductError] = useState("");
  const [scope, setScope] = useState("all");
  const [search, setSearch] = useState("");
  useEffect(() => { fetch("/api/products").then(async response => { const data = await response.json(); if (!response.ok || !data.success) throw new Error(); setProducts(data.data); }).catch(() => setProductError("Products could not be loaded. Refresh before choosing specific products.")); }, []);
  useEffect(() => {
    if (!id) return;
    fetch(`/api/coupons/${id}`).then(async response => { const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message); const c = data.data;
      const date = (value: string | null) => value ? new Date(value).toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" }) : "";
      setForm({ code: c.code, description: c.description ?? "", type: c.type, value: String(c.value), minimumOrder: c.minimumOrder ?? "", maximumDiscount: c.maximumDiscount ?? "", usageLimit: c.usageLimit == null ? "" : String(c.usageLimit), startsAt: date(c.startsAt), expiresAt: date(c.expiresAt), active: c.active, rules: { ...blank.rules, ...c.rules, mode: c.rules?.mode ?? (c.rules?.productIds?.length ? "selected" : "same_price") } });
      setScope(c.rules?.productIds?.length ? "selected" : "all");
    }).catch(cause => setError(cause.message)).finally(() => setLoading(false));
  }, [id]);
  const update = (key: keyof Form, value: string | boolean) => { if (key === "type" && value === "buy_get") setScope(form.rules.mode === "selected" ? "selected" : "all"); setForm(current => ({ ...current, [key]: value })); };
  const rules = (patch: Partial<OfferRules>) => setForm(current => ({ ...current, rules: { ...current.rules, ...patch } }));
  async function save(event: React.FormEvent) {
    event.preventDefault(); setError("");
    if (scope === "selected" && !form.rules.productIds.length) { setError("Select at least one eligible product."); return; }
    setSaving(true);
    try {
      const response = await fetch(id ? `/api/coupons/${id}` : "/api/coupons", { method: id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, value: Number(form.value), minimumOrder: form.minimumOrder === "" ? null : Number(form.minimumOrder), maximumDiscount: form.maximumDiscount === "" ? null : Number(form.maximumDiscount), usageLimit: form.usageLimit === "" ? null : Number(form.usageLimit), rules: { ...form.rules, productIds: scope === "all" ? [] : form.rules.productIds } }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.message || "Unable to save offer."); router.push("/admin/coupons"); router.refresh();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save offer."); } finally { setSaving(false); }
  }
  const preview = { code: form.code, type: form.type, value: Number(form.value), minimum: Number(form.minimumOrder), maximum: form.maximumDiscount ? Number(form.maximumDiscount) : null, rules: { ...form.rules, productIds: scope === "all" ? [] : form.rules.productIds } };
  if (loading) return <p className="p-6">Loading offer…</p>;
  return <main className="min-h-screen bg-[#faf8f6] p-4 sm:p-6"><Link href="/admin/coupons" className="text-sm text-[#857974]">← Back to offers</Link><h1 className="mt-5 text-2xl font-semibold text-[#292321]">{id ? "Edit offer" : "Create offer"}</h1><p className="mt-2 max-w-3xl text-sm text-[#857974]">Offers appear on product pages, in the cart and at checkout. Only one offer applies per order.</p>
    <form onSubmit={save} className="mt-6 max-w-5xl space-y-5">
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Storefront presentation</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">
      <Field label="Offer page heading"><input maxLength={100} value={form.rules.heading ?? ""} onChange={e => rules({ heading: e.target.value })} placeholder="E.g. Shirts, two for ₹1,099" /></Field>
      <Field label="Banner image URL or uploaded image path"><input value={form.rules.bannerImage ?? ""} onChange={e => rules({ bannerImage: e.target.value })} placeholder="/uploads/banners/offer.jpg" /></Field>
      <Field label="Card priority (0–100)"><input type="number" min={0} max={100} value={form.rules.priority ?? 0} onChange={e => rules({ priority: Number(e.target.value) })} /></Field>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.rules.showOnCards !== false} onChange={e => rules({ showOnCards: e.target.checked })} />Show offer on eligible product cards</label>
    </div><p className="mt-3 text-xs text-gray-500">Higher priority appears first. Equal priorities use the lowest achievable per-item price. Amounts and conditions are calculated automatically from the rules below.</p>{form.code && <Link href={`/offer/${encodeURIComponent(form.code)}`} target="_blank" className="mt-3 inline-block text-sm underline">Preview saved offer page ↗</Link>}</section>
    <section className="rounded-xl border border-[#eee6e1] bg-white p-5 sm:p-6"><div className="grid gap-5 sm:grid-cols-2">
      <Field label="Offer code"><input required maxLength={40} value={form.code} onChange={e => update("code", e.target.value.toUpperCase())} /></Field>
      <Field label="Offer type"><select value={form.type} onChange={e => update("type", e.target.value)}><option value="percentage">Percentage off</option><option value="fixed">Fixed amount off</option><option value="buy_get">Buy X, get Y free</option><option value="quantity_price">Quantity-based price</option><option value="quantity_discount">Quantity-based fixed discount</option></select></Field>
      {["percentage", "fixed"].includes(form.type) && <Field label={form.type === "percentage" ? "Discount percentage" : "Discount amount (₹)"}><input type="number" required min="0.01" step="0.01" max={form.type === "percentage" ? 100 : 1000000} value={form.value} onChange={e => update("value", e.target.value)} /></Field>}
      <Field label="Minimum cart value (₹, optional)"><input type="number" min="0" step="0.01" value={form.minimumOrder} onChange={e => update("minimumOrder", e.target.value)} /></Field>
      <Field label="Maximum saving (₹, optional)"><input type="number" min="0.01" step="0.01" value={form.maximumDiscount} onChange={e => update("maximumDiscount", e.target.value)} /></Field>
      <Field label="Usage limit (optional)"><input type="number" min="1" step="1" value={form.usageLimit} onChange={e => update("usageLimit", e.target.value)} /></Field>
      <Field label="Starts on (India time)"><input type="date" value={form.startsAt} onChange={e => update("startsAt", e.target.value)} /></Field><Field label="Expires at end of day (India time)"><input type="date" value={form.expiresAt} onChange={e => update("expiresAt", e.target.value)} /></Field>
    </div></section>
    {form.type === "buy_get" && <section className="rounded-xl border border-[#eee6e1] bg-white p-5"><h2 className="font-semibold">Buy X, get Y free</h2><div className="mt-4"><Field label="Offer mode"><select value={form.rules.mode ?? "same_price"} onChange={e => { rules({ mode: e.target.value as "same_price" | "selected" }); setScope(e.target.value === "selected" ? "selected" : "all"); }}><option value="same_price">Automatic — same current selling price</option><option value="selected">Selected products — mixed prices allowed</option></select></Field>{form.rules.mode === "selected" && <Field label="Free-item calculation"><select value={form.rules.freeRule ?? "cheapest"} onChange={e => rules({ freeRule: e.target.value as "cheapest" | "specific" })}><option value="cheapest">Cheapest selected items are free</option><option value="specific">Only designated gift products are free</option></select></Field>}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Buy quantity"><input required type="number" min={1} max={100} value={form.rules.buyQuantity} onChange={e => rules({ buyQuantity: Number(e.target.value) })} /></Field><Field label="Free quantity"><input required type="number" min={1} max={100} value={form.rules.getQuantity} onChange={e => rules({ getQuantity: Number(e.target.value) })} /></Field></div><p className="mt-3 text-xs leading-5 text-[#857974]">Buy 1 get 1 requires 2 eligible items in the bag. Buy 2 get 1 requires 3. Automatic mode groups items by their current selling price. Selected mode follows your free-item calculation. Free products must be added to the cart by the customer.</p></section>}
    {["quantity_price", "quantity_discount"].includes(form.type) && <section className="rounded-xl border border-[#eee6e1] bg-white p-5"><h2 className="font-semibold">{form.type === "quantity_discount" ? "Quantity discount tiers" : "Quantity price tiers"}</h2>{form.type === "quantity_price" && <div className="mt-4"><Field label="Price means"><select value={form.rules.priceMode} onChange={e => rules({ priceMode: e.target.value as "unit" | "bundle" })}><option value="unit">Price per eligible item</option><option value="bundle">Total price per complete bundle</option></select></Field></div>}<div className="mt-4 space-y-3">{form.rules.tiers?.map((tier,index) => <div key={index} className="grid grid-cols-[1fr_1fr_auto] items-end gap-3"><Field label="Minimum quantity"><input type="number" required min={1} max={1000} value={tier.quantity} onChange={e => rules({ tiers: form.rules.tiers?.map((row,i) => i === index ? { ...row, quantity: Number(e.target.value) } : row) })} /></Field><Field label={form.type === "quantity_discount" ? "Discount amount (₹)" : form.rules.priceMode === "unit" ? "Each item (₹)" : "Bundle total (₹)"}><input type="number" required min="0.01" step="0.01" value={tier.price} onChange={e => rules({ tiers: form.rules.tiers?.map((row,i) => i === index ? { ...row, price: Number(e.target.value) } : row) })} /></Field><button type="button" aria-label={`Remove tier ${index + 1}`} disabled={form.rules.tiers?.length === 1} onClick={() => rules({ tiers: form.rules.tiers?.filter((_,i) => i !== index) })} className="h-11 px-2 text-sm text-rose-700 disabled:opacity-30">Remove</button></div>)}</div><button type="button" disabled={(form.rules.tiers?.length ?? 0) >= 20} onClick={() => rules({ tiers: [...(form.rules.tiers ?? []), { quantity: (form.rules.tiers?.at(-1)?.quantity ?? 0) + 1, price: 299 }] })} className="mt-4 text-sm font-medium text-[#9b5c5c]">+ Add quantity tier</button><p className="mt-3 text-xs leading-5 text-[#857974]">The highest qualifying tier wins. Fixed discounts apply once per order; the subtotal must remain positive. Price tiers retain their per-item or complete-bundle calculation.</p></section>}
    <section className="rounded-xl border border-[#eee6e1] bg-white p-5"><h2 className="font-semibold">Eligible products</h2><div className="mt-3 flex gap-5 text-sm"><label><input type="radio" name="scope" checked={scope === "all"} disabled={form.type === "buy_get"} onChange={() => setScope("all")} /> All products</label><label><input type="radio" name="scope" checked={scope === "selected"} disabled={form.type === "buy_get"} onChange={() => setScope("selected")} /> Selected products</label></div>{scope === "selected" && <div className="mt-4"><input aria-label="Search eligible products" placeholder="Search product name or SKU" value={search} onChange={e => setSearch(e.target.value)} className="h-11 w-full rounded-lg border px-3 text-sm" /><p className="mt-2 text-xs text-[#857974]">{form.rules.productIds.length} products selected. Quantities can be mixed across the selection.</p>{productError && <p className="mt-2 text-xs text-red-700">{productError}</p>}<div className="mt-3 max-h-64 overflow-y-auto rounded-lg border">{products.filter(product => (product.name + product.sku).toLowerCase().includes(search.toLowerCase())).map(product => <label key={product.id} className="flex items-center gap-3 border-b p-3 text-sm last:border-0"><input type="checkbox" checked={form.rules.productIds.includes(product.id)} onChange={e => rules({ productIds: e.target.checked ? [...form.rules.productIds, product.id] : form.rules.productIds.filter(value => value !== product.id) })} /><span>{product.name}<span className="block text-xs text-[#857974]">{product.sku} · ₹{product.price} · {product.status}</span></span></label>)}</div></div>}</section>
    {form.type === "buy_get" && form.rules.mode === "selected" && form.rules.freeRule === "specific" && <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Designated free products</h2><p className="mt-2 text-xs text-gray-500">Selected gift products do not count towards the paid quantity. Customers add the gifts to their bag.</p>{products.filter(product => form.rules.productIds.includes(product.id)).map(product => <label key={product.id} className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={form.rules.freeProductIds?.includes(product.id) ?? false} onChange={e => rules({ freeProductIds: e.target.checked ? [...(form.rules.freeProductIds ?? []), product.id] : form.rules.freeProductIds?.filter(id => id !== product.id) })} />{product.name}</label>)}</section>}
    <section className="rounded-xl border border-[#eee6e1] bg-white p-5"><Field label="Description (optional)"><textarea rows={3} maxLength={500} value={form.description} onChange={e => update("description", e.target.value)} /></Field><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e => update("active", e.target.checked)} />Active and available to customers</label></section>
    <section className="rounded-xl border border-[#E8DADA] bg-[#FAF5F2] p-5"><p className="text-xs font-semibold uppercase tracking-wider text-[#9b5c5c]">Customer preview</p><h2 className="mt-2 font-serif text-xl">{offerTitle(preview)}</h2><p className="mt-2 text-sm leading-6 text-[#857974]">{offerTerms(preview)}</p></section>
    {error && <p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-3"><Link href="/admin/coupons" className="rounded-lg border px-5 py-3 text-sm">Cancel</Link><button disabled={saving} className="rounded-lg bg-[#292321] px-5 py-3 text-sm text-white disabled:opacity-50">{saving ? "Saving…" : "Save offer"}</button></div>
    </form></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-[#4d4541]">{label}<span className="mt-2 block [&_input]:h-11 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-[#e1d9d5] [&_input]:px-3 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-[#e1d9d5] [&_select]:px-3 [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:p-3">{children}</span></label>; }
