"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Request = { id: number; kind: string; status: string; reason: string };
type Shipment = { id: number; carrier: string; trackingNumber: string; status: string; deliveredAt: string | null };
type Order = { status: string; items: { id: number; productName: string; quantity: number; shipmentId: number | null; returnEnabled: boolean; replacementEnabled: boolean; returnDays: number; replacementDays: number; serviceRequest: Request | null }[]; shipments: Shipment[] };

export default function OrderFulfillment({ orderId, onUpdated }: { orderId: string; onUpdated: () => void }) {
  const router = useRouter();
  const [order, setOrder] = useState<Order | null>(null);
  const [selected, setSelected] = useState<number[]>([]);
  const [carrier, setCarrier] = useState("");
  const [trackingNumber, setTracking] = useState("");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [deliveryDates, setDeliveryDates] = useState<Record<number, string>>({});
  const [notes, setNotes] = useState<Record<number, string>>({});
  const [trackingEdit, setTrackingEdit] = useState<{ id: number; carrier: string; trackingNumber: string } | null>(null);
  const [revision, setRevision] = useState(0);
  useEffect(() => { fetch(`/api/orders/${orderId}`).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.message); setOrder(result.data); }).catch(error => setMessage(error.message)); }, [orderId, revision]);
  async function update(path: string, method: string, body: object) {
    setBusy(true); setMessage("");
    try { const response = await fetch(`/api/orders/${orderId}/${path}`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setRevision(value => value + 1); setSelected([]); setTrackingEdit(null); onUpdated(); router.refresh(); setMessage("Updated successfully."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update."); } finally { setBusy(false); }
  }
  return <section className="m-5 space-y-5 rounded-xl border bg-white p-5"><div><h2 className="text-lg font-semibold">Shipments & after-sales requests</h2><p className="mt-1 text-sm text-gray-500">Select one or more complete product lines for each parcel. Separate parcels have separate delivery dates and return windows.</p>{order && <p className="mt-2 text-sm font-medium capitalize">Order: {order.status.replaceAll("_", " ")}</p>}</div>
    {order && <><div className="grid gap-3 sm:grid-cols-2">{order.items.map(item => <div key={item.id} className="rounded-xl border border-[#E8DADA] p-4"><p className="font-medium">{item.productName} · Qty {item.quantity}</p><p className="mt-2 text-xs text-gray-500">{item.returnEnabled ? `${item.returnDays}-day returns` : "Non-returnable"} · {item.replacementEnabled ? `${item.replacementDays}-day replacement` : "No replacement"}</p>{order.shipments.some(shipment => shipment.id === item.shipmentId && shipment.status === "delivered" && shipment.deliveredAt) && order.status !== "cancelled" ? <a href={`/api/account/order-items/${item.id}/invoice`} download className="mt-3 inline-block text-sm font-medium text-[#9b5c5c] underline">Download item invoice</a> : <p className="mt-3 text-xs text-gray-500">Invoice becomes available after delivery.</p>}</div>)}</div><form className="space-y-4 rounded-xl bg-gray-50 p-4" onSubmit={event => { event.preventDefault(); void update("shipments", "POST", { itemIds: selected, carrier, trackingNumber }); }}><h3 className="font-medium">Create shipment</h3>{order.items.filter(item => !item.shipmentId).map(item => <label key={item.id} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={e => setSelected(current => e.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))} />{item.productName} · Qty {item.quantity}</label>)}{order.items.every(item => item.shipmentId) && <p className="text-sm text-gray-500">All items have a shipment.</p>}<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Courier / carrier<input required maxLength={100} value={carrier} onChange={e => setCarrier(e.target.value)} className="mt-1 block w-full rounded-lg border p-3" /></label><label className="text-sm">Tracking number<input required maxLength={150} value={trackingNumber} onChange={e => setTracking(e.target.value)} className="mt-1 block w-full rounded-lg border p-3" /></label></div><button disabled={busy || !selected.length} className="rounded-lg bg-[#9b5c5c] px-5 py-3 text-sm text-white disabled:opacity-40">Create shipment</button></form>
      {order.shipments.map(shipment => <div key={shipment.id} className="rounded-xl border p-4"><h3 className="font-semibold">Shipment #{shipment.id} · <span className="capitalize">{shipment.status}</span></h3><p className="mt-2 text-sm">{shipment.carrier} · {shipment.trackingNumber}</p><button type="button" disabled={busy || order.status === "cancelled"} onClick={() => setTrackingEdit({ id: shipment.id, carrier: shipment.carrier, trackingNumber: shipment.trackingNumber })} className="mt-2 text-xs text-[#9b5c5c] underline">Edit tracking details</button>{trackingEdit?.id === shipment.id && <form className="mt-3 grid gap-3 rounded-lg bg-[#FAF5F2] p-3" onSubmit={event => { event.preventDefault(); void update("shipments", "PUT", { shipmentId: trackingEdit.id, carrier: trackingEdit.carrier, trackingNumber: trackingEdit.trackingNumber }); }}><label className="text-xs">Courier<input required maxLength={100} value={trackingEdit.carrier} onChange={event => setTrackingEdit({ ...trackingEdit, carrier: event.target.value })} className="mt-1 block w-full rounded border p-2" /></label><label className="text-xs">Tracking number<input required maxLength={150} value={trackingEdit.trackingNumber} onChange={event => setTrackingEdit({ ...trackingEdit, trackingNumber: event.target.value })} className="mt-1 block w-full rounded border p-2" /></label><div className="flex gap-3"><button disabled={busy} className="rounded bg-[#9b5c5c] px-3 py-2 text-xs text-white">Save tracking</button><button type="button" onClick={() => setTrackingEdit(null)} className="text-xs">Cancel</button></div></form>}<p className="mt-1 text-sm text-gray-500">{order.items.filter(item => item.shipmentId === shipment.id).map(item => `${item.productName} × ${item.quantity}`).join(", ")}</p>{shipment.deliveredAt ? <p className="mt-2 text-sm">Delivered: {new Date(shipment.deliveredAt).toLocaleString("en-IN")}</p> : <div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-sm">Actual delivery date (blank = now)<input type="datetime-local" value={deliveryDates[shipment.id] || ""} onChange={e => setDeliveryDates({ ...deliveryDates, [shipment.id]: e.target.value })} className="mt-1 block rounded-lg border p-3" /></label><button type="button" disabled={busy} onClick={() => void update("shipments", "PATCH", { shipmentId: shipment.id, deliveredAt: deliveryDates[shipment.id] ? new Date(deliveryDates[shipment.id]).toISOString() : undefined })} className="rounded-lg bg-green-700 px-4 py-3 text-sm text-white disabled:opacity-50">Mark delivered</button></div>}</div>)}
      {order.items.filter(item => item.serviceRequest).map(item => { const request = item.serviceRequest!; return <div key={request.id} className="rounded-xl border p-4"><h3 className="font-semibold capitalize">{request.kind} · {request.status}</h3><p className="mt-1 text-sm">{item.productName}</p><p className="mt-3 whitespace-pre-line text-sm text-gray-600">{request.reason}</p>{!["completed", "rejected"].includes(request.status) && <><label className="mt-3 block text-sm">Customer-visible note<textarea maxLength={1000} value={notes[request.id] || ""} onChange={e => setNotes({ ...notes, [request.id]: e.target.value })} className="mt-1 block w-full rounded-lg border p-3" /></label><div className="mt-3 flex flex-wrap gap-2">{(request.status === "requested" ? ["approved", "rejected"] : ["completed"]).map(status => <button key={status} type="button" disabled={busy} onClick={() => void update("service-requests", "PATCH", { requestId: request.id, status, adminNote: notes[request.id] })} className="rounded-lg border px-4 py-3 text-sm capitalize disabled:opacity-50">Mark {status}</button>)}</div><p className="mt-2 text-xs text-gray-500">Completing a request records its resolution; arrange any refund or replacement dispatch separately.</p></>}</div>; })}
    </>}{message && <p role="status" className="text-sm">{message}</p>}
  </section>;
}
