"use client";

import { useEffect, useMemo, useState } from "react";

type Category = { id: number; name: string; slug: string; parentId: number | null };
type Product = { id: number; name: string; sku: string; categoryId: number; inStock: boolean };
type Feed = { id: string; name: string; slug: string; username: string; active: boolean; country: string; language: string; lastGeneratedAt?: string; productCount: number; issues: string[]; url: string; selection: { productIds: number[]; categoryIds: number[]; featured: boolean; badged: boolean; inStockOnly: boolean } };
type Form = { id?: string; name: string; slug: string; username: string; password: string; active: boolean; country: string; language: string; selection: Feed["selection"] };
const blank = (): Form => ({ name: "", slug: "", username: "", password: "", active: true, country: "IN", language: "en", selection: { productIds: [], categoryIds: [], featured: false, badged: false, inStockOnly: true } });

export default function ProductFeedManager() {
  const [feeds, setFeeds] = useState<Feed[]>([]); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [form, setForm] = useState<Form>(blank); const [query, setQuery] = useState(""); const [status, setStatus] = useState("Loading feeds…"); const [busy, setBusy] = useState(false);
  const editing = Boolean(form.id);
  const selected = useMemo(() => new Set(form.selection.productIds), [form.selection.productIds]);
  const visibleProducts = useMemo(() => products.filter(product => `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase())).slice(0, 80), [products, query]);
  const load = async () => { try { const response = await fetch("/api/admin/product-feeds", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setFeeds(data.feeds); setProducts(data.products); setCategories(data.categories); setStatus(""); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to load feeds."); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const patch = (value: Partial<Form>) => setForm(current => ({ ...current, ...value }));
  const patchSelection = (value: Partial<Form["selection"]>) => patch({ selection: { ...form.selection, ...value } });
  const toggleId = (field: "productIds" | "categoryIds", id: number) => patchSelection({ [field]: form.selection[field].includes(id) ? form.selection[field].filter(item => item !== id) : [...form.selection[field], id] });
  const edit = (feed: Feed) => { setForm({ id: feed.id, name: feed.name, slug: feed.slug, username: feed.username, password: "", active: feed.active, country: feed.country, language: feed.language, selection: feed.selection }); setStatus("Password is hidden. Enter a new one only to rotate it."); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setStatus(""); try { const response = await fetch("/api/admin/product-feeds", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { id: form.id, feed: form } : form) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setForm(blank()); setStatus(editing ? "Feed updated." : "Feed created. Copy its URL into Meta Commerce Manager."); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to save feed."); } finally { setBusy(false); } };
  const generate = async (id: string) => { setBusy(true); setStatus(""); try { const response = await fetch("/api/admin/product-feeds", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: "generate" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setStatus(`Feed generated: ${data.validation.productCount} eligible products, ${data.validation.issues.length} warnings.`); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not generate feed."); } finally { setBusy(false); } };
  const copyUrl = async (url: string) => { try { await navigator.clipboard.writeText(url); setStatus("Feed URL copied. Enter the username and password in Meta Commerce Manager."); } catch { setStatus("Could not copy automatically. Select the feed URL and copy it manually."); } };
  const remove = async (id: string) => { if (!window.confirm("Delete this feed configuration? Its URL will stop working.")) return; setBusy(true); try { const response = await fetch(`/api/admin/product-feeds?id=${encodeURIComponent(id)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw new Error(data.message); if (form.id === id) setForm(blank()); setStatus("Feed deleted."); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not delete feed."); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#f7f8fa] p-4 text-gray-900 sm:p-8"><div className="mx-auto max-w-7xl"><div className="mb-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-gray-500">Catalog integrations</p><h1 className="mt-2 text-3xl font-bold">Meta Product Feeds</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-600">Create protected XML catalog feeds for Meta Commerce Manager. Prices and availability are read from the live Vayziq catalog whenever Meta fetches the URL.</p></div>
    <form onSubmit={save} className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{editing ? "Edit feed" : "Create Meta feed"}</h2><p className="mt-1 text-xs text-gray-500">Passwords are saved as a one-way hash and cannot be viewed again.</p></div>{editing && <button type="button" onClick={() => { setForm(blank()); setStatus(""); }} className="rounded-lg border px-3 py-2 text-xs font-semibold">Cancel edit</button>}</div>
      <div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Feed name"><input required value={form.name} onChange={e => patch({ name: e.target.value })} placeholder="Meta India Catalog" /></Field><Field label="Feed URL slug"><input required value={form.slug} onChange={e => patch({ slug: e.target.value })} placeholder="meta-india" /><span>URL: https://vayziq.com/feeds/meta/{form.slug || "feed-slug"}.xml</span></Field><Field label="Feed username"><input required autoComplete="off" value={form.username} onChange={e => patch({ username: e.target.value })} placeholder="meta_catalog" /></Field><Field label={editing ? "New password (leave blank to retain)" : "Feed password"}><input required={!editing} minLength={12} autoComplete="new-password" type="password" value={form.password} onChange={e => patch({ password: e.target.value })} placeholder="At least 12 characters" /></Field><Field label="Country"><input required maxLength={2} value={form.country} onChange={e => patch({ country: e.target.value.toUpperCase() })} /></Field><Field label="Language"><input required maxLength={8} value={form.language} onChange={e => patch({ language: e.target.value.toLowerCase() })} /></Field></div>
      <section className="mt-7 border-t pt-6"><h3 className="font-semibold">Choose products for this feed</h3><p className="mt-1 text-xs text-gray-500">With no category or product selected, every active product is included. Parent categories include their subcategories; selected categories and products are combined.</p><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-600">Categories</p><div className="max-h-52 space-y-1 overflow-auto rounded-xl border p-3">{categories.map(category => <label key={category.id} className="flex items-center gap-2 rounded p-1.5 text-sm hover:bg-gray-50"><input type="checkbox" checked={form.selection.categoryIds.includes(category.id)} onChange={() => toggleId("categoryIds", category.id)} /><span>{category.parentId ? "↳ " : ""}{category.name}</span></label>)}</div></div><div><div className="flex items-center justify-between gap-2"><p className="text-xs font-semibold uppercase tracking-wide text-gray-600">Individual products</p><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name or SKU" className="h-8 w-44 rounded border px-2 text-xs" /></div><div className="mt-2 max-h-52 space-y-1 overflow-auto rounded-xl border p-3">{visibleProducts.map(product => <label key={product.id} className="flex items-center gap-2 rounded p-1.5 text-sm hover:bg-gray-50"><input type="checkbox" checked={selected.has(product.id)} onChange={() => toggleId("productIds", product.id)} /><span className="min-w-0 truncate">{product.name} <small className="text-gray-500">· {product.sku}{!product.inStock ? " · Out of stock" : ""}</small></span></label>)}</div></div></div>
      <div className="mt-4 flex flex-wrap gap-4 text-sm"><Toggle label="Only in-stock products" value={form.selection.inStockOnly} onChange={value => patchSelection({ inStockOnly: value })} /><Toggle label="Only featured products" value={form.selection.featured} onChange={value => patchSelection({ featured: value })} /><Toggle label="Only badge products" value={form.selection.badged} onChange={value => patchSelection({ badged: value })} /><Toggle label="Feed active" value={form.active} onChange={value => patch({ active: value })} /></div></section>
      <div className="mt-6 flex flex-wrap items-center gap-3"><button disabled={busy} className="rounded-xl bg-black px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : editing ? "Save feed" : "Create protected feed"}</button><p role="status" className="text-sm text-gray-600">{status}</p></div></form>
    <section className="mt-7 overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="border-b px-5 py-4 sm:px-7"><h2 className="font-semibold">Configured feeds</h2></div>{feeds.length === 0 ? <p className="p-8 text-sm text-gray-500">No Meta feeds have been created yet.</p> : <div className="divide-y">{feeds.map(feed => <article key={feed.id} className="p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{feed.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${feed.active ? "bg-emerald-100 text-emerald-800" : "bg-gray-100 text-gray-600"}`}>{feed.active ? "Active" : "Paused"}</span></div><code className="mt-2 block break-all text-xs text-gray-600">{feed.url}</code><p className="mt-1 text-xs text-gray-500">Username: <span className="font-medium text-gray-700">{feed.username}</span> · password is hidden</p><p className="mt-2 text-xs text-gray-500">{feed.productCount} eligible products · {feed.issues.length} validation warnings · {feed.lastGeneratedAt ? `Last generated ${new Date(feed.lastGeneratedAt).toLocaleString()}` : "Not generated yet"}</p>{feed.issues.length > 0 && <p className="mt-2 text-xs text-amber-700">{feed.issues.slice(0, 3).join(" · ")}</p>}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void copyUrl(feed.url)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Copy URL</button><button type="button" disabled={busy} onClick={() => void generate(feed.id)} className="rounded-lg bg-amber-300 px-3 py-2 text-xs font-semibold">Generate</button><button type="button" onClick={() => edit(feed)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Edit</button><button type="button" disabled={busy} onClick={() => void remove(feed.id)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Delete</button></div></div></article>)}</div>}</section></div></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium">{label}<span className="mt-2 block [&>input]:h-11 [&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-gray-300 [&>input]:px-3 [&>input]:font-normal">{children}</span></label>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-2"><input type="checkbox" checked={value} onChange={e => onChange(e.target.checked)} />{label}</label>; }
