"use client";

import { useEffect, useState } from "react";
import { Mail, Pencil, Phone, Save, User } from "lucide-react";

type Profile = { name: string; email: string; mobile: string | null };

export default function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [form, setForm] = useState({ name: "", email: "" });
  const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const load = async () => { const response = await fetch("/api/account/profile"); if (!response.ok) return; const data = (await response.json()) as { user: Profile }; setProfile(data.user); setForm({ name: data.user.name, email: data.user.email.endsWith("@account.susmitas.local") ? "" : data.user.email }); }; void load(); }, []);
  const save = async () => { setSaving(true); setMessage(""); try { const response = await fetch("/api/account/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = (await response.json()) as { user?: Profile; message?: string }; if (!response.ok || !data.user) { setMessage(data.message || "Unable to update profile."); return; } setProfile(data.user); setEditing(false); setMessage("Profile updated successfully."); } finally { setSaving(false); } };
  return <main><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-gray-500">My Account</p><h1 className="mt-1 text-2xl font-semibold text-gray-900">My Profile</h1><p className="mt-1 text-sm text-gray-500">Manage your personal information.</p></div><button className="inline-flex items-center gap-2 rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-medium text-gray-700 hover:border-[#c98a8a]" onClick={() => setEditing(true)} type="button"><Pencil className="h-4 w-4" />Edit</button></div>
    <section className="rounded-2xl border border-gray-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3 border-b border-gray-100 pb-5"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#b56f6f]/10"><User className="h-6 w-6 text-[#9b5c5c]" /></div><div><h2 className="font-semibold text-gray-900">{profile?.name || "Customer"}</h2><p className="text-xs text-gray-500">Verified customer</p></div></div>{editing ? <div className="mt-6 space-y-4"><label className="block text-sm font-medium text-gray-700">Full name<input className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-[#b56f6f]" onChange={(event) => setForm({ ...form, name: event.target.value })} value={form.name} /></label><label className="block text-sm font-medium text-gray-700">Email address<input className="mt-2 w-full rounded-xl border border-gray-200 px-4 py-3 outline-none focus:border-[#b56f6f]" onChange={(event) => setForm({ ...form, email: event.target.value })} type="email" value={form.email} /></label><p className="text-xs text-gray-500">Mobile number is verified through OTP and cannot be changed here.</p><div className="flex gap-3"><button className="rounded-xl bg-[#9b5c5c] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-60" disabled={saving} onClick={() => void save()} type="button"><Save className="mr-2 inline h-4 w-4" />{saving ? "Saving..." : "Save Changes"}</button><button className="text-sm text-gray-600" onClick={() => setEditing(false)} type="button">Cancel</button></div></div> : <dl className="mt-6 divide-y divide-gray-100"><Row icon={<User className="h-4 w-4" />} label="Full name" value={profile?.name || "—"} /><Row icon={<Mail className="h-4 w-4" />} label="Email address" value={profile?.email.endsWith("@account.susmitas.local") ? "Not added" : profile?.email || "Not added"} /><Row icon={<Phone className="h-4 w-4" />} label="Mobile number" value={profile?.mobile ? `+91 ${profile.mobile}` : "Not added"} /></dl>}{message && <p className="mt-4 text-sm text-[#9b5c5c]">{message}</p>}</section></main>;
}
function Row({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 py-4"><span className="text-gray-400">{icon}</span><div><dt className="text-xs text-gray-400">{label}</dt><dd className="mt-1 text-sm font-medium text-gray-900">{value}</dd></div></div>; }
