"use client";

import {
  ChangeEvent,
  FormEvent,
  useEffect,
  useState,
} from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function NewCategoryPage() {
  const router = useRouter();

  const [name, setName] = useState("");
  const [slug, setSlug] = useState("");
  const [description, setDescription] = useState("");
  const [status, setStatus] = useState("Active");
  const [featured, setFeatured] = useState(false);
  const [image, setImage] = useState("");
  const [parentId, setParentId] = useState("");
  const [parentCategories, setParentCategories] = useState<Array<{ id: number; name: string; slug: string; parentId: number | null; status: string }>>([]);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/categories", { cache: "no-store" })
      .then((response) => response.json())
      .then((result) => {
        if (!cancelled && result?.success && Array.isArray(result.categories)) {
          setParentCategories(result.categories.filter((item: { parentId: number | null; status: string }) => item.parentId === null && item.status === "active"));
        }
      })
      .catch(() => undefined);
    return () => { cancelled = true; };
  }, []);

  const useSubcategoryDemo = () => {
    setName("Silk Sarees");
    setSlug("silk-sarees");
    setParentId(String(parentCategories.find((item) => item.slug === "sarees")?.id ?? ""));
    setDescription("Demo subcategory under Sarees. Add products to this collection to feature it in the store.");
  };
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  // =====================================================
  // NAME -> SLUG
  // =====================================================

  const handleNameChange = (value: string) => {
    setName(value);

    const generatedSlug = value
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-");

    setSlug(generatedSlug);
  };

  // =====================================================
  // IMAGE PREVIEW
  // =====================================================

  const handleImageUpload = async (
  e: ChangeEvent<HTMLInputElement>
) => {
  const file = e.target.files?.[0];

  if (!file) return;

  try {
    setError("");

    const previewUrl =
      URL.createObjectURL(file);

    setImage(previewUrl);

    const formData = new FormData();

    formData.append("file", file);

    const response = await fetch(
      "/api/upload/category",
      {
        method: "POST",
        credentials: "include",
        body: formData,
      }
    );

    const result = await response.json();

    if (!response.ok || !result?.success) {
      throw new Error(
        result?.message ||
          "Failed to upload image."
      );
    }

    setImage(result.image);
  } catch (error) {
    console.error(
      "IMAGE UPLOAD ERROR:",
      error
    );

    setImage("");

    setError(
      error instanceof Error
        ? error.message
        : "Failed to upload image."
    );
  }
};

  const removeImage = () => {
    setImage("");
  };

  // =====================================================
  // SAVE CATEGORY
  // =====================================================

  const handleSubmit = async (
    e: FormEvent<HTMLFormElement>
  ) => {
    e.preventDefault();

    setError("");

    const cleanName = name.trim();
    const cleanSlug = slug.trim().toLowerCase();
    const cleanDescription =
      description.trim();

    if (!cleanName) {
      setError("Category name is required.");
      return;
    }

    if (!cleanSlug) {
      setError("URL slug is required.");
      return;
    }

    setSaving(true);

    try {
      const payload = {
        name: cleanName,
        slug: cleanSlug,
        description:
          cleanDescription || null,

        // Prisma enum values
        status:
          status === "Active"
            ? "active"
            : "inactive",

        featured,
        parentId: parentId ? Number(parentId) : null,

        /*
         * IMPORTANT:
         *
         * This is currently only a browser
         * object URL generated by URL.createObjectURL().
         *
         * It is useful for preview but is NOT
         * a permanent server image URL.
         */
        image: image || null,
      };

      console.log(
        "CREATE CATEGORY PAYLOAD:",
        payload
      );

      const response = await fetch(
        "/api/categories",
        {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type":
              "application/json",
          },
          body: JSON.stringify(payload),
        }
      );

      const result =
        await response.json();

      console.log(
        "CREATE CATEGORY RESPONSE:",
        result
      );

      if (
        !response.ok ||
        !result?.success
      ) {
        throw new Error(
          result?.message ||
            "Unable to create category."
        );
      }

      // Go back to category list
      router.push("/admin/categories");

      router.refresh();
    } catch (err) {
      console.error(
        "CREATE CATEGORY ERROR:",
        err
      );

      setError(
        err instanceof Error
          ? err.message
          : "Unable to create category."
      );
    } finally {
      setSaving(false);
    }
  };

  // =====================================================
  // UI
  // =====================================================

  return (
    <div className="min-h-full">

      {/* =================================================
          PAGE HEADER
      ================================================= */}

      <div className="border-b border-[#eee6e1] bg-white">
        <div className="px-5 py-6 lg:px-8">

          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">

            <div>
              <p className="text-xs font-medium uppercase tracking-[0.18em] text-[#b56f6f]">
                Catalog
              </p>

              <h1 className="mt-1 text-2xl font-semibold tracking-tight text-[#292321]">
                Add Category
              </h1>

              <p className="mt-1 text-sm text-[#8f8580]">
                Create a new product category.
              </p>
            </div>

            <Link
              href="/admin/categories"
              className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-[#e5ddd8] bg-white px-4 text-sm font-medium text-[#514945] transition hover:border-[#b56f6f] hover:text-[#b56f6f]"
            >
              <ArrowLeftIcon />
              Back to Categories
            </Link>

          </div>

        </div>
      </div>

      {/* =================================================
          FORM
      ================================================= */}

      <form onSubmit={handleSubmit}>

        <div className="p-5 lg:p-8">

          <div className="mx-auto max-w-5xl">

            {/* ERROR */}

            {error && (
              <div className="mb-6 rounded-xl border border-red-100 bg-red-50 px-4 py-3">
                <p className="text-sm text-red-600">
                  {error}
                </p>
              </div>
            )}

            <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">

              {/* =================================================
                  MAIN
              ================================================= */}

              <div className="space-y-6 lg:col-span-2">

                {/* CATEGORY INFORMATION */}

                <section className="rounded-xl border border-[#eee6e1] bg-white">

                  <div className="border-b border-[#eee6e1] px-5 py-4">

                    <h2 className="text-sm font-semibold text-[#292321]">
                      Category Information
                    </h2>

                    <p className="mt-1 text-xs text-[#958b86]">
                      Enter the basic information for this category.
                    </p>

                  </div>

                  <div className="space-y-5 p-5">

                    {/* NAME */}

                    <div>

                      <label
                        htmlFor="name"
                        className="mb-2 block text-xs font-medium text-[#514945]"
                      >
                        Category Name
                        <span className="ml-1 text-red-500">
                          *
                        </span>
                      </label>

                      <input
                        id="name"
                        type="text"
                        value={name}
                        onChange={(e) =>
                          handleNameChange(
                            e.target.value
                          )
                        }
                        placeholder="e.g. Sarees"
                        required
                        disabled={saving}
                        className="h-11 w-full rounded-lg border border-[#e5ddd8] bg-white px-4 text-sm text-[#292321] outline-none placeholder:text-[#aaa09a] focus:border-[#b56f6f] disabled:bg-[#faf8f6]"
                      />

                    </div>

                    {/* SLUG */}

                    <div>

                      <label
                        htmlFor="slug"
                        className="mb-2 block text-xs font-medium text-[#514945]"
                      >
                        URL Slug
                        <span className="ml-1 text-red-500">
                          *
                        </span>
                      </label>

                      <div className="flex">

                        <span className="flex h-11 items-center rounded-l-lg border border-r-0 border-[#e5ddd8] bg-[#faf8f6] px-3 text-sm text-[#958b86]">
                          /
                        </span>

                        <input
                          id="slug"
                          type="text"
                          value={slug}
                          onChange={(e) =>
                            setSlug(
                              e.target.value
                                .toLowerCase()
                                .replace(
                                  /[^a-z0-9-]/g,
                                  ""
                                )
                            )
                          }
                          placeholder="sarees"
                          required
                          disabled={saving}
                          className="h-11 min-w-0 flex-1 rounded-r-lg border border-[#e5ddd8] bg-white px-4 text-sm text-[#292321] outline-none placeholder:text-[#aaa09a] focus:border-[#b56f6f] disabled:bg-[#faf8f6]"
                        />

                      </div>

                      <p className="mt-2 text-[11px] text-[#aaa09a]">
                        This will be used in the category URL.
                      </p>

                    </div>

                    <div>
                      <div className="mb-2 flex items-center justify-between gap-3">
                        <label htmlFor="parentCategory" className="block text-xs font-medium text-[#514945]">Parent category</label>
                        <button type="button" onClick={useSubcategoryDemo} disabled={!parentCategories.length || saving} className="text-[11px] font-semibold text-[#9F5E5E] underline underline-offset-2 disabled:opacity-50">Try demo: Silk Sarees</button>
                      </div>
                      <select id="parentCategory" value={parentId} onChange={(event) => setParentId(event.target.value)} disabled={saving} className="h-11 w-full rounded-lg border border-[#e5ddd8] bg-white px-4 text-sm text-[#292321] outline-none focus:border-[#b56f6f] disabled:bg-[#faf8f6]">
                        <option value="">No parent · top-level category</option>
                        {parentCategories.map((item) => <option key={item.id} value={String(item.id)}>{item.name}</option>)}
                      </select>
                      <p className="mt-2 text-[11px] text-[#958b86]">Choose a parent to show this subcategory under it in navigation. The demo fills “Silk Sarees” under Sarees.</p>
                    </div>

                    {/* DESCRIPTION */}

                    <div>

                      <label
                        htmlFor="description"
                        className="mb-2 block text-xs font-medium text-[#514945]"
                      >
                        Description
                      </label>

                      <textarea
                        id="description"
                        value={description}
                        onChange={(e) =>
                          setDescription(
                            e.target.value
                          )
                        }
                        rows={6}
                        disabled={saving}
                        placeholder="Write a short description for this category..."
                        className="w-full resize-none rounded-lg border border-[#e5ddd8] bg-white px-4 py-3 text-sm leading-6 text-[#292321] outline-none placeholder:text-[#aaa09a] focus:border-[#b56f6f] disabled:bg-[#faf8f6]"
                      />

                      <p className="mt-2 text-[11px] text-[#aaa09a]">
                        A short description helps customers understand the category.
                      </p>

                    </div>

                  </div>

                </section>

                {/* =================================================
                    IMAGE
                ================================================= */}

                <section className="rounded-xl border border-[#eee6e1] bg-white">

                  <div className="border-b border-[#eee6e1] px-5 py-4">

                    <h2 className="text-sm font-semibold text-[#292321]">
                      Category Image
                    </h2>

                    <p className="mt-1 text-xs text-[#958b86]">
                      Upload an image to represent this category.
                    </p>

                  </div>

                  <div className="p-5">

                    {image ? (

                      <div className="relative max-w-md overflow-hidden rounded-xl border border-[#e5ddd8] bg-[#faf8f6]">

                        <div className="aspect-[4/3]">

                          <img
                            src={image}
                            alt={
                              name ||
                              "Category image"
                            }
                            className="h-full w-full object-cover"
                          />

                        </div>

                        <button
                          type="button"
                          onClick={removeImage}
                          disabled={saving}
                          className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-white text-red-500 shadow-md transition hover:bg-red-50 disabled:opacity-50"
                          aria-label="Remove image"
                        >
                          <XIcon />
                        </button>

                      </div>

                    ) : (

                      <label className="flex min-h-[260px] cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-[#d8cfca] bg-[#fcfaf9] transition hover:border-[#b56f6f] hover:bg-[#faf5f3]">

                        <div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#b56f6f]/10 text-[#b56f6f]">
                          <UploadIcon />
                        </div>

                        <span className="mt-4 text-sm font-medium text-[#514945]">
                          Upload Category Image
                        </span>

                        <span className="mt-1 text-xs text-[#aaa09a]">
                          JPG, PNG or WEBP
                        </span>

                        <span className="mt-1 text-[11px] text-[#b0a6a1]">
                          Recommended: 800 × 600 px
                        </span>

                        <input
                          type="file"
                          accept="image/jpeg,image/png,image/webp"
                          onChange={
                            handleImageUpload
                          }
                          className="hidden"
                        />

                      </label>

                    )}

                  </div>

                </section>

              </div>

              {/* =================================================
                  SIDEBAR
              ================================================= */}

              <div className="space-y-6">

                {/* STATUS */}

                <section className="rounded-xl border border-[#eee6e1] bg-white">

                  <div className="border-b border-[#eee6e1] px-5 py-4">

                    <h2 className="text-sm font-semibold text-[#292321]">
                      Category Status
                    </h2>

                  </div>

                  <div className="space-y-4 p-5">

                    <div>

                      <label
                        htmlFor="status"
                        className="mb-2 block text-xs font-medium text-[#514945]"
                      >
                        Status
                      </label>

                      <select
                        id="status"
                        value={status}
                        onChange={(e) =>
                          setStatus(
                            e.target.value
                          )
                        }
                        disabled={saving}
                        className="h-11 w-full rounded-lg border border-[#e5ddd8] bg-white px-4 text-sm text-[#514945] outline-none focus:border-[#b56f6f]"
                      >

                        <option value="Active">
                          Active
                        </option>

                        <option value="Inactive">
                          Inactive
                        </option>

                      </select>

                    </div>

                    {/* FEATURED */}

                    <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-[#eee6e1] p-3">

                      <input
                        type="checkbox"
                        checked={featured}
                        onChange={(e) =>
                          setFeatured(
                            e.target.checked
                          )
                        }
                        disabled={saving}
                        className="mt-0.5 h-4 w-4 accent-[#b56f6f]"
                      />

                      <span>

                        <span className="block text-xs font-medium text-[#514945]">
                          Featured Category
                        </span>

                        <span className="mt-1 block text-[11px] leading-4 text-[#aaa09a]">
                          Show this category in featured sections.
                        </span>

                      </span>

                    </label>

                  </div>

                </section>

                {/* =================================================
                    PREVIEW
                ================================================= */}

                <section className="rounded-xl border border-[#eee6e1] bg-white">

                  <div className="border-b border-[#eee6e1] px-5 py-4">

                    <h2 className="text-sm font-semibold text-[#292321]">
                      Preview
                    </h2>

                  </div>

                  <div className="p-5">

                    <div className="overflow-hidden rounded-xl border border-[#eee6e1]">

                      <div className="aspect-[4/3] bg-[#f4efec]">

                        {image ? (

                          <img
                            src={image}
                            alt="Preview"
                            className="h-full w-full object-cover"
                          />

                        ) : (

                          <div className="flex h-full items-center justify-center text-xs text-[#aaa09a]">
                            No image
                          </div>

                        )}

                      </div>

                      <div className="p-4">

                        <p className="text-sm font-semibold text-[#292321]">
                          {name ||
                            "Category Name"}
                        </p>

                        <p className="mt-1 text-xs text-[#958b86]">
                          {description ||
                            "Category description will appear here."}
                        </p>

                      </div>

                    </div>

                  </div>

                </section>

                {/* =================================================
                    ACTIONS
                ================================================= */}

                <div className="rounded-xl border border-[#eee6e1] bg-white p-5">

                  <button
                    type="submit"
                    disabled={saving}
                    className="flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#292321] px-5 text-sm font-medium text-white transition hover:bg-[#403936] disabled:cursor-not-allowed disabled:opacity-60"
                  >

                    {saving ? (
                      <>
                        <SpinnerIcon />
                        Saving...
                      </>
                    ) : (
                      <>
                        <SaveIcon />
                        Save Category
                      </>
                    )}

                  </button>

                  <Link
                    href="/admin/categories"
                    className="mt-3 flex h-11 w-full items-center justify-center rounded-lg border border-[#e5ddd8] text-sm font-medium text-[#514945] transition hover:border-[#b56f6f] hover:text-[#b56f6f]"
                  >
                    Cancel
                  </Link>

                </div>

              </div>

            </div>

          </div>

        </div>

      </form>

    </div>
  );
}


/* =====================================================
   ICONS
===================================================== */

function ArrowLeftIcon() {
  return (
    <svg
      width="17"
      height="17"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function UploadIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M12 16V4" />
      <path d="m7 9 5-5 5 5" />
      <path d="M5 20h14" />
    </svg>
  );
}

function XIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

function SaveIcon() {
  return (
    <svg
      width="17"
      height="17"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2Z" />
      <path d="M17 21v-8H7v8" />
      <path d="M7 3v5h8" />
    </svg>
  );
}

function SpinnerIcon() {
  return (
    <svg
      width="17"
      height="17"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="animate-spin"
      aria-hidden="true"
    >
      <path d="M12 2v4" />
      <path d="m16.24 3.76-2.83 2.83" />
      <path d="M22 12h-4" />
      <path d="m20.24 16.24-2.83-2.83" />
      <path d="M12 22v-4" />
      <path d="m7.76 20.24 2.83-2.83" />
      <path d="M2 12h4" />
      <path d="m3.76 7.76 2.83 2.83" />
    </svg>
  );
}