"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { placements } from "@/components/admin/BannerEditor";
type Banner={id:number;title:string;image:string;placement:string;sortOrder:number;active:boolean;link:string|null};
type ActiveCategory={name:string;slug:string};
export default function BannersPage(){
 const [banners,setBanners]=useState<Banner[]>([]),[placement,setPlacement]=useState("home"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[categories,setCategories]=useState<ActiveCategory[]>([]);
 useEffect(()=>{fetch("/api/categories?status=active").then(async r=>{const d=await r.json();if(r.ok)setCategories(d.categories);});},[]);
 useEffect(()=>{fetch("/api/banners").then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message);setBanners(d.data);}).catch(e=>setError(e.message));},[]);
 async function change(method:string,body:object){setBusy(true);setError("");try{const r=await fetch("/api/banners",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.message);const refreshed=await fetch("/api/banners");const data=await refreshed.json();setBanners(data.data);}catch(e){setError(e instanceof Error?e.message:"Update failed.");}finally{setBusy(false);}}
 const placementOptions=[...Object.entries(placements),...categories.map(category=>[`category:${category.slug}`,`${category.name} slider`] as [string,string])];
 const shown=banners.filter(b=>b.placement===placement).sort((a,b)=>a.sortOrder-b.sortOrder||a.id-b.id);
 function move(index:number,delta:number){const ids=shown.map(b=>b.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void change("PATCH",{ids});}
 return <main className="min-h-screen bg-[#faf8f6] p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold">Banners &amp; Offer Zone</h1><p className="mt-2 text-sm text-[#857974]">Manage clickable slides for each page. Offer Zone cards appear on Home only.</p></div><Link href="/admin/banners/new" className="rounded-lg bg-[#292321] px-5 py-3 text-sm text-white">Add banner</Link></div><select aria-label="Banner placement" value={placement} onChange={e=>setPlacement(e.target.value)} className="my-6 h-11 rounded-lg border bg-white px-3">{placementOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}<div className="space-y-4">{shown.map((banner,index)=><article key={banner.id} className="flex flex-col gap-4 rounded-xl border bg-white p-4 sm:flex-row sm:items-center"><img src={banner.image} alt={banner.title || "Banner"} className="h-28 w-full rounded-lg object-cover sm:w-56" /><div className="min-w-0 flex-1"><h2 className="font-semibold">{banner.title || "Untitled banner"}</h2><p className="mt-1 break-all text-xs text-[#857974]">{banner.link || "No destination"}</p><p className="mt-2 text-xs">{banner.active?"Enabled":"Disabled"} · Position {index+1}</p></div><div className="flex flex-wrap items-center gap-3 text-sm"><button aria-label="Move banner up" disabled={busy||index===0} onClick={()=>move(index,-1)} className="h-10 rounded border px-3 disabled:opacity-30">↑</button><button aria-label="Move banner down" disabled={busy||index===shown.length-1} onClick={()=>move(index,1)} className="h-10 rounded border px-3 disabled:opacity-30">↓</button><Link href={`/admin/banners/${banner.id}`} className="underline">Edit</Link><button disabled={busy} onClick={()=>void change("PATCH",{id:banner.id,active:!banner.active})}>{banner.active?"Disable":"Enable"}</button><button disabled={busy} onClick={()=>{if(window.confirm("Delete this banner?"))void change("DELETE",{id:banner.id});}} className="text-red-700">Delete</button></div></article>)}{!shown.length&&<p className="rounded-xl border bg-white p-6 text-sm text-[#857974]">No banners in this placement. Add your first image.</p>}</div></main>;
}
